# Generated by Django 4.2.7 on 2023-11-07 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_studentsponsor_sponsor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami formati noto'g'ri. Raqamni '9' va '15' belgidan iborat bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
            ],
        ),
    ]
