# Generated by Django 4.2.7 on 2023-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_phonenumber_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='^\\+998\\d{9}$', max_length=50, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
